import { Prisma } from '../generated/prisma';

export interface StandardPlanSpec {
  name: string;
  tier: 'starter' | 'growth' | 'enterprise';
  billingInterval: 'monthly';
  currency: 'NGN' | 'GHS' | 'KES' | 'ZAR';
  basePriceMinorUnits: number;
  features: Record<string, unknown>;
  customTerms?: Record<string, unknown> | null;
}

export const STANDARD_PLAN_CATALOG: StandardPlanSpec[] = [
  {
    name: 'Starter',
    tier: 'starter',
    billingInterval: 'monthly',
    currency: 'NGN',
    basePriceMinorUnits: 1_500_000,
    features: {
      operatingUnitCap: 1,
      vehicleCap: 10,
      driverCap: 15,
      seatLimit: 3,
      verificationEnabled: false,
      walletEnabled: false,
      intelligenceEnabled: false,
      supportTier: 'email',
    },
  },
  {
    name: 'Starter',
    tier: 'starter',
    billingInterval: 'monthly',
    currency: 'GHS',
    basePriceMinorUnits: 15_000,
    features: {
      operatingUnitCap: 1,
      vehicleCap: 10,
      driverCap: 15,
      seatLimit: 3,
      verificationEnabled: false,
      walletEnabled: false,
      intelligenceEnabled: false,
      supportTier: 'email',
    },
  },
  {
    name: 'Starter',
    tier: 'starter',
    billingInterval: 'monthly',
    currency: 'KES',
    basePriceMinorUnits: 250_000,
    features: {
      operatingUnitCap: 1,
      vehicleCap: 10,
      driverCap: 15,
      seatLimit: 3,
      verificationEnabled: false,
      walletEnabled: false,
      intelligenceEnabled: false,
      supportTier: 'email',
    },
  },
  {
    name: 'Starter',
    tier: 'starter',
    billingInterval: 'monthly',
    currency: 'ZAR',
    basePriceMinorUnits: 35_000,
    features: {
      operatingUnitCap: 1,
      vehicleCap: 10,
      driverCap: 15,
      seatLimit: 3,
      verificationEnabled: false,
      walletEnabled: false,
      intelligenceEnabled: false,
      supportTier: 'email',
    },
  },
  {
    name: 'Growth',
    tier: 'growth',
    billingInterval: 'monthly',
    currency: 'NGN',
    basePriceMinorUnits: 3_500_000,
    features: {
      operatingUnitCap: 5,
      vehicleCap: 20,
      vehicleOverageRateMinorUnits: 150_000,
      driverCap: null,
      seatLimit: 25,
      verificationEnabled: true,
      verificationsIncluded: 10,
      verificationRateMinorUnits: 60_000,
      walletEnabled: true,
      intelligenceEnabled: true,
      supportTier: 'whatsapp_email',
    },
  },
  {
    name: 'Growth',
    tier: 'growth',
    billingInterval: 'monthly',
    currency: 'GHS',
    basePriceMinorUnits: 35_000,
    features: {
      operatingUnitCap: 5,
      vehicleCap: 20,
      vehicleOverageRateMinorUnits: 1_500,
      driverCap: null,
      seatLimit: 25,
      verificationEnabled: true,
      verificationsIncluded: 10,
      walletEnabled: true,
      intelligenceEnabled: true,
      supportTier: 'whatsapp_email',
    },
  },
  {
    name: 'Growth',
    tier: 'growth',
    billingInterval: 'monthly',
    currency: 'KES',
    basePriceMinorUnits: 550_000,
    features: {
      operatingUnitCap: 5,
      vehicleCap: 20,
      vehicleOverageRateMinorUnits: 25_000,
      driverCap: null,
      seatLimit: 25,
      verificationEnabled: true,
      verificationsIncluded: 10,
      walletEnabled: true,
      intelligenceEnabled: true,
      supportTier: 'whatsapp_email',
    },
  },
  {
    name: 'Growth',
    tier: 'growth',
    billingInterval: 'monthly',
    currency: 'ZAR',
    basePriceMinorUnits: 80_000,
    features: {
      operatingUnitCap: 5,
      vehicleCap: 20,
      vehicleOverageRateMinorUnits: 3_500,
      driverCap: null,
      seatLimit: 25,
      verificationEnabled: true,
      verificationsIncluded: 10,
      walletEnabled: true,
      intelligenceEnabled: true,
      supportTier: 'whatsapp_email',
    },
  },
  {
    name: 'Enterprise',
    tier: 'enterprise',
    billingInterval: 'monthly',
    currency: 'NGN',
    basePriceMinorUnits: 0,
    features: {
      operatingUnitCap: null,
      vehicleCap: null,
      driverCap: null,
      seatLimit: null,
      verificationEnabled: true,
      walletEnabled: true,
      intelligenceEnabled: true,
      whiteLabelAvailable: true,
      ssoAvailable: true,
      supportTier: 'dedicated',
      assistedUpgradeOnly: true,
    },
    customTerms: {
      pricingModel: 'custom_quote_required',
      minimumFleetSize: 50,
      contactSalesRequired: true,
    },
  },
  {
    name: 'Enterprise',
    tier: 'enterprise',
    billingInterval: 'monthly',
    currency: 'GHS',
    basePriceMinorUnits: 0,
    features: {
      operatingUnitCap: null,
      vehicleCap: null,
      driverCap: null,
      seatLimit: null,
      verificationEnabled: true,
      walletEnabled: true,
      intelligenceEnabled: true,
      whiteLabelAvailable: true,
      ssoAvailable: true,
      supportTier: 'dedicated',
      assistedUpgradeOnly: true,
    },
    customTerms: {
      pricingModel: 'custom_quote_required',
      minimumFleetSize: 50,
      contactSalesRequired: true,
    },
  },
  {
    name: 'Enterprise',
    tier: 'enterprise',
    billingInterval: 'monthly',
    currency: 'KES',
    basePriceMinorUnits: 0,
    features: {
      operatingUnitCap: null,
      vehicleCap: null,
      driverCap: null,
      seatLimit: null,
      verificationEnabled: true,
      walletEnabled: true,
      intelligenceEnabled: true,
      whiteLabelAvailable: true,
      ssoAvailable: true,
      supportTier: 'dedicated',
      assistedUpgradeOnly: true,
    },
    customTerms: {
      pricingModel: 'custom_quote_required',
      minimumFleetSize: 50,
      contactSalesRequired: true,
    },
  },
  {
    name: 'Enterprise',
    tier: 'enterprise',
    billingInterval: 'monthly',
    currency: 'ZAR',
    basePriceMinorUnits: 0,
    features: {
      operatingUnitCap: null,
      vehicleCap: null,
      driverCap: null,
      seatLimit: null,
      verificationEnabled: true,
      walletEnabled: true,
      intelligenceEnabled: true,
      whiteLabelAvailable: true,
      ssoAvailable: true,
      supportTier: 'dedicated',
      assistedUpgradeOnly: true,
    },
    customTerms: {
      pricingModel: 'custom_quote_required',
      minimumFleetSize: 50,
      contactSalesRequired: true,
    },
  },
];

export function toPlanJsonValue(
  value: Record<string, unknown> | null | undefined,
): Prisma.InputJsonValue | Prisma.NullableJsonNullValueInput {
  if (value == null) {
    return Prisma.JsonNull;
  }
  return value as Prisma.InputJsonValue;
}
